CREATE DATABASE db;
USE db;

CREATE SCHEMA v_t_gg_sj_goods_out_schema
source type CSV
fields(
"goodsid" 				type string,
"deptid" 				type string,
"packnum" 				type string,
"barcode" 				type string,
"goodslocid" 			type string,
"stocktype" 			type string,
"ownerid" 				type string,
"ownername" 			type string,
"goodsownermanageno" 	type string,
"inbillid" 				type string,
"goodsownerpackno" 		type string,
"manageno" 				type string,
"feebegindate" 			type DATETIME,
"contractid" 			type string,
"goodsstateno" 			type string,
"goodsstatename" 		type string,
"changeownertimes" 		type double,
"goodstype" 			type string,
"goodstypename" 		type string,
"kindno" 				type string,
"kindname" 				type string,
"shopsignid" 			type string,
"shopsignname" 			type string,
"prodareaid" 			type string,
"prodareaname" 			type string,
"goodsbatchno" 			type string,
"prodstoveno" 			type string,
"gradenum" 				type string,
"gradenumthick" 		type double,
"gradenumwidth" 		type double,
"gradenumlength" 		type double,
"grossweight" 			type double,
"netweight" 			type double,
"poundweight" 			type double,
"checkweight" 			type double,
"sheetnum" 				type double,
"unit" 					type string,
"packtype" 				type string,
"stockareaid" 			type string,
"qualitymemo" 			type string,
"firstinownerid" 		type string,
"firstindate" 			type DATETIME,
"outbillid" 			type string,
"ldglistid" 			type string,
"materialgoodsid" 		type string,
"intype" 				type string,
"outtype" 				type string,
"billstate" 			type double,
"outbilltime" 			type DATETIME,
"memo" 					type string,
"extsysplanobjectid" 	type string,
"extsyskindid" 			type string,
"extsysshopsignid" 		type string,
"extsysprodareaid" 		type string,
"foreignlistno"			type string,
"sendflag" 				type double,
"r_record_create_date" 	type DATETIME,
"r_record_create_user" 	type string,
"r_record_update_date" 	type DATETIME,
"r_record_update_user" 	type string,
"r_record_is_deleted" 	type double,
"incusttime" 			type DATETIME,
"sidemark" 				type string,
"temp" 					type string,
"length_product_max" 	type double,
"heat_num" 				type string,
"test_lot_num" 			type string,
"r_record_change_flag" 	type double,
"sdprice" 				type string,
"extsysgradenum" 		type string,
"collectionmanname" 	type string,
"lockflag" 				type string,
"check_type" 			type string,
"outdate" 				type DATETIME,
"yfweight" 				type double,
"yfsheet" 				type double,
"pregoodsid" 			type string,
"issplit" 				type double,
"gradenumxh" 			type double,
"gradenumwhdw" 			type string,
"splittime" 			type double,
"isclear" 				type double,
"singlesheetnum" 		type double,
"gradenumhz" 			type string,
"gradenumthickhz" 		type double,
"singlesheet" 			type double,
"loclv1" 				type string,
"singlesheetunit" 		type string,
"dcemp" 				type string,
"qzemp" 				type string,
"dcemp2" 				type string,
"shipno" 				type string,
"shipname" 				type string,
"shipcd" 				type string,
"shiplevel" 			type string,
"cmmemo" 				type string,
"cmmemock" 				type string,
"shopsigncd" 			type string,
"processtypename" 		type string,
"packtypename" 			type string,
"sort_emp" 				type string,
"customerid" 			type string,
"lvgoodsid" 			type string,
"dispersesheet" 		type double,
"dbdeptid" 				type string,
"dbcustomer"			type string,
"dbgulender"			type string,
"locked_object" 		type string,
"locked_date" 			type DATETIME,
"unlocked_date" 		type DATETIME,
"preownername" 			type string,
"ply" 					type double,
"tdstate" 				type string,
"opselected" 			type string,
"oplock" 				type string,
"opinupload" 			type string,
"opchangeupload" 		type string,
"opinbatchid" 			type string,
"opchangebatchid" 		type string,
"opinupload_date" 		type DATETIME,
"out_package_status" 	type string,
"out_package_desc" 		type string,
"gmpacktype" 			type string,
"handno" 				type string,
"saveno" 				type string,
"drawno" 				type string,
"dangerouslevel" 		type string,
"acceptancecriteria" 	type string,
"shippingmark" 			type string,
"loclv2" 				type string,
"payedflag" 			type string,
"ordergoodsownerid" 	type string,
"ordergoodsownername" 	type string 
)
RECORD DELIMITER "CRLF"
FIELD DELIMITER ","
TEXT QUALIFIER "DQM";

CREATE PARSER v_t_gg_sj_goods_out_parser
TYPE rcd
SCHEMA v_t_gg_sj_goods_out_schema;

CREATE TABLE v_t_gg_sj_goods_out using v_t_gg_sj_goods_out_parser; 

create index v_t_gg_sj_goods_out_index on table v_t_gg_sj_goods_out(goodsid);

CREATE MAP v_t_gg_sj_goods_out_map ON table v_t_gg_sj_goods_out
KEY (deptid) 
VALUE (netweight)
TYPE string;

CREATE MAP v_t_gg_sj_goods_out1_map ON table v_t_gg_sj_goods_out
KEY (deptid) 
VALUE (packnum)
TYPE string;

CREATE SCHEMA t_gg_tx_dl_bil_d_schema
SOURCE TYPE CSV
FIELDS(
"seg_no" 					type string,
"accset_no" 				type double,
"user_seg_no" 				type string,
"user_id" 					type string,
"bill_date1" 				type string,
"internal_flag" 			type string,
"internal_seg_no" 			type string,
"resource_num" 				type string,
"bill_status" 				type string,
"bill_num" 					type string,
"valid_start_date" 			type DATETIME ,
"valid_end_date" 			type DATETIME ,
"bill_date" 				type DATETIME ,
"wprovider_id" 				type string,
"wprovider_name" 			type string,
"unit_weight" 				type string,
"netweight" 				type string,
"wprovider_tele" 			type string,
"wprovider_zip" 			type string,
"out_settle_type2" 			type string,
"customer_id" 				type string,
"contract_id" 				type string,
"delivery_type" 			type string,
"freight_settle_type"		type string,
"out_settle_type1" 			type string,
"car_type" 					type string,
"special_request" 			type string,
"consignee_id" 				type string,
"consignee_name" 			type string,
"consignee_addr" 			type string,
"consignee_respnder" 		type string,
"consignee_tele" 			type string,
"consignee_fax" 			type string,
"consignee_zipcode" 		type string,
"trans_flag" 				type string,
"tprovider_id" 				type string,
"create_person" 			type string,
"create_date" 				type DATETIME,
"return_person" 			type string,
"return_date" 				type DATETIME,
"out_settle_type" 			type string,
"bill_back_date" 			type DATETIME,
"printed" 					type double,
"bill_print_site" 			type string,
"bill_print_user_id" 		type string,
"bill_print_date" 			type DATETIME,
"arrear_type" 				type string,
"settle_seq_num" 			type double,
"modi_person" 				type string,
"modi_date" 				type DATETIME ,
"return_confirm_flag" 		type string,
"return_confirm_pers" 		type string,
"return_confirm_date" 		type DATETIME ,
"print_batch_id" 			type string,
"fetch_person" 				type string,
"fetch_person_id_card" 		type string,
"bill_dessent_type" 		type string,
"start_privince" 			type string,
"delivery_privince" 		type string,
"group_commission_id" 		type string,
"approve_status" 			type string,
"bill_batch_id" 			type string,
"random_id" 				type string,
"provider_name" 			type string,
"provider_id" 				type string,
"ebs_bill_type" 			type string,
"ebs_bill_print_user_name"	type string,
"ebs_bill_print_org_name" 	type string,
"remark" 					type string,
"ebs_bill_lock" 			type string,
"ebs_bill_object" 			type string,
"proxy_flag" 				type string,
"z_plan_apply_date" 		type DATETIME,
"ebs_bill_batch_id" 		type string,
"ws_flag" 					type string,
"ws_date" 					type DATETIME,
"proc_mark" 				type string,
"insert_time" 				type DATETIME,
"downloadflag" 				type string,
"pack_num" 					type double,
"factory_product_id" 		type string,
"plan_count" 				type double,
"optflag" 					type string,
"free_store_start_date" 	type DATETIME,
"free_store_end_date" 		type DATETIME,
"free_store_day" 			type double,
"first_print_date" 			type DATETIME,
"hosing_price" 				type double,
"owner_num1" 				type string,
"dept_id" 					type string,
"deptid" 					type string,
"owner_num" 				type string,
"prod_area" 				type string,
"shopsign" 					type double,
"gradenum" 					type string,
"spec1" 					type string,
"spec3" 					type string,
"spec5" 					type string,
"contract_transfer_flag" 	type string,
"customer_name" 			type string,
"settle_flag" 				type string,
"hoisting_cost" 			type double,
"free_storage_date" 		type string,
"source_seg_no" 			type string,
"need_feedback" 			type string,
"electron_bill" 			type string,
"storefee_remark" 			type string,
"tax_num" 					type string,
"invoice_acct_num" 			type string,
"invoice_bank"				type string,
"invoice_tele"				type string,
"ivoice_addr" 				type string,
"actuser_id" 				type string,
"actuser_name" 				type string,
"vf_netweight" type `expr` data type string value iilmap("v_t_gg_sj_goods_out_map",deptid),
"vf_packnum" type `expr` data type string value iilmap("v_t_gg_sj_goods_out1_map",deptid)
)
RECORD DELIMITER "CRLF"
FIELD DELIMITER ","
TEXT QUALIFIER "DQM";

CREATE PARSER t_gg_tx_dl_bil_d_parser
TYPE rcd
SCHEMA t_gg_tx_dl_bil_d_schema;

CREATE TABLE t_t using t_gg_tx_dl_bil_d_parser; 

create index t_gg_tx_dl_bil_d_index on table t_t(bill_status);

CREATE STATISTICS MODEL t_t_model ON TABLE t_t
group by(bill_date,resource_num,bill_num,out_settle_type,deptid,owner_num)
MEASURES(sum(shopsign),sum(vf_netweight),count(pack_num),count(vf_packnum));

