SELECT
	OWNERID,
	OWNERNAME,
	MANAGENO,
	GOODSOWNERMANAGENO,
	PACKNUM,
	GRADENUM,
	GOODSLOCID,
	KINDNAME,
	SHOPSIGNNAME,
	PRODAREANAME,
	FIRSTINDATE,
	SUM (GRADENUMXH) GRADENUMXH,
	SUM (SINGLESHEETNUM) SINGLESHEETNUM,
	SUM (NETWEIGHT) NETWEIGHT,
	SUM (GROSSWEIGHT) GROSSWEIGHT,
	SUM (SHEETNUM) SHEETNUM
FROM
	(
		SELECT
			OWNERID,
			OWNERNAME,
			MANAGENO,
			GOODSOWNERMANAGENO,
			PACKNUM,
			GRADENUM,
			GOODSLOCID,
			KINDNAME,
			SHOPSIGNNAME,
			PRODAREANAME,
			FIRSTINDATE,
			SUM (GRADENUMXH) GRADENUMXH,
			SUM (SINGLESHEETNUM) SINGLESHEETNUM,
			SUM (NETWEIGHT) NETWEIGHT,
			SUM (GROSSWEIGHT) GROSSWEIGHT,
			SUM (SHEETNUM) SHEETNUM
		FROM
			T_GG_SJ_GOODS
		WHERE
			GOODSSTATENO = '110'
		AND R_RECORD_IS_DELETED = 0
		AND DEPTID = '101'
		GROUP BY
			OWNERID,
			OWNERNAME,
			MANAGENO,
			GOODSOWNERMANAGENO,
			PACKNUM,
			GRADENUM,
			GOODSLOCID,
			KINDNAME,
			SHOPSIGNNAME,
			PRODAREANAME,
			FIRSTINDATE
		
	UNION ALL
	
		SELECT
			OWNERID,
			OWNERNAME,
			MANAGENO,
			GOODSOWNERMANAGENO,
			PACKNUM,
			GRADENUM,
			GOODSLOCID,
			KINDNAME,
			SHOPSIGNNAME,
			PRODAREANAME,
			FIRSTINDATE,
			SUM (GRADENUMXH) GRADENUMXH,
			SUM (SINGLESHEETNUM) SINGLESHEETNUM,
			- SUM (NETWEIGHT) NETWEIGHT ,
			- SUM (GROSSWEIGHT) GROSSWEIGHT ,
			- SUM (SHEETNUM) SHEETNUM
		FROM
			T_ZY_RK_INBILLDETAIL
		WHERE
			DEPTID = '101'
		AND GOODSSTATENO = '20'
		AND FIRSTINDATE >= TO_DATE ('2011/7/2', 'YYYY-MM-DD')
		GROUP BY
			OWNERID,
			OWNERNAME,
			MANAGENO,
			GOODSOWNERMANAGENO,
			PACKNUM,
			GRADENUM,
			GOODSLOCID,
			KINDNAME,
			SHOPSIGNNAME,
			PRODAREANAME,
			FIRSTINDATE
			
	UNION ALL
	
		SELECT
			OWNERID,
			OWNERNAME,
			MANAGENO,
			GOODSOWNERMANAGENO,
			PACKNUM,
			GRADENUM,
			GOODSLOCID,
			KINDNAME,
			SHOPSIGNNAME,
			PRODAREANAME,
			FIRSTINDATE,
			0 GRADENUMXH,
			0 SINGLESHEETNUM,
			- SUM (NETWEIGHT) NETWEIGHT ,
			- SUM (GROSSWEIGHT) GROSSWEIGHT ,
			- SUM (SHEETNUM) SHEETNUM
		FROM
			T_ZY_JG_PROCARTICLEDTL
		WHERE
			DEPTID = '101'
		AND FIRSTINDATE >= TO_DATE ('2011/7/2', 'YYYY-MM-DD')
		AND GOODSSTATENO = '130'
		GROUP BY
			OWNERID,
			OWNERNAME,
			MANAGENO,
			GOODSOWNERMANAGENO,
			PACKNUM,
			GRADENUM,
			GOODSLOCID,
			KINDNAME,
			SHOPSIGNNAME,
			PRODAREANAME,
			FIRSTINDATE
			
	UNION ALL
	
		SELECT
			NEWOWNERNO OWNERID,
			NEWOWNERNAME OWNERNAME,
			MANAGENUM MANAGENO,
			GOODSOWNERMANAGENO,
			PACKNUM,
			GRADENUM,
			GOODSLOCID,
			KINDNAME,
			SHOPSIGNNAME,
			PRODAREANAME,
			FIRSTINDATE,
			0 GRADENUMXH,
			0 SINGLESHEETNUM,
			- SUM (NETWEIGHT) NETWEIGHT ,
			- SUM (GROSSWEIGHT) GROSSWEIGHT ,
			- SUM (SHEETNUM) SHEETNUM
		FROM
			(
				SELECT
					A .NEWOWNERNO,
					A .NEWOWNERNAME,
					(CASE WHEN ( MANAGENUM IS NULL OR MANAGENUM = '') THEN	PREMANAGENUM ELSE MANAGENUM	END	) MANAGENUM,
					B.SHOPSIGNID,
					B.SHOPSIGNNAME,
					B.PRODAREAID,
					B.PRODAREANAME,
					B.GRADENUM,
					B.NETWEIGHT,
					B.GROSSWEIGHT,
					B.SHEETNUM,
					B.FIRSTINDATE,
					B.KINDNAME,
					B.GOODSLOCID,
					B.PACKNUM,
					B.GOODSOWNERMANAGENUM GOODSOWNERMANAGENO
				FROM
					(
						SELECT
							DEPTID,
							CHANGEOWNERID,
							NEWOWNERNO,
							NEWOWNERNAME
						FROM
							T_ZY_GH_CHANGEOWNERLIST
						WHERE
							DEPTID = '101'
						AND CHANGEDATE >= TO_DATE ('2012/7/2', 'YYYY-MM-DD')
					) A,
					T_ZY_GH_CHANGEOWNERDETAIL B
				WHERE
					A .CHANGEOWNERID = B.CHANGEOWNERNO
				AND A .DEPTID = B.DEPTID
			) TB1
		GROUP BY
			NEWOWNERNO,
			NEWOWNERNAME,
			MANAGENUM,
			GOODSOWNERMANAGENO,
			PACKNUM,
			GRADENUM,
			GOODSLOCID,
			KINDNAME,
			SHOPSIGNNAME,
			PRODAREANAME,
			FIRSTINDATE
			
	UNION ALL
	
		SELECT
			OWNERNO,
			OWNERNAME,
			MANAGENUM MANAGENO,
			GOODSOWNERMANAGENUM GOODSOWNERMANAGENO,
			PACKNUM,
			GRADENUM,
			GOODSLOCID,
			KINDNAME,
			SHOPSIGNNAME,
			PRODAREANAME,
			FIRSTINDATE,
			SUM (GRADENUMXH) GRADENUMXH,
			SUM (SINGLESHEETNUM) SINGLESHEETNUM,
			SUM (NETWEIGHT) NETWEIGHT,
			SUM (GROSSWEIGHT) GROSSWEIGHT,
			SUM (SHEETNUM) SHEETNUM
		FROM
			T_ZY_CK_OUTPACK
		WHERE
			DEPTID = '101'
		AND OUTCUSTTIME >= TO_DATE ('2012/7/2', 'YYYY-MM-DD')
		GROUP BY
			OWNERNO,
			OWNERNAME,
			MANAGENUM,
			GOODSOWNERMANAGENUM,
			PACKNUM,
			GRADENUM,
			GOODSLOCID,
			KINDNAME,
			SHOPSIGNNAME,
			PRODAREANAME,
			FIRSTINDATE
			
	UNION ALL
	
		SELECT											
			OWNERID,
			OWNERNAME,
			MANAGENO,
			GOODSOWNERMANAGENO,
			A .PACKNUM,
			GRADENUM,
			GOODSLOCID,
			KINDNAME,
			SHOPSIGNNAME,
			PRODAREANAME,
			FIRSTINDATE,
			SUM (GRADENUMXH) GRADENUMXH,
			SUM (SINGLESHEETNUM) SINGLESHEETNUM,
			SUM (NETWEIGHT) NETWEIGHT,
			SUM (GROSSWEIGHT) GROSSWEIGHT,
			SUM (SHEETNUM) SHEETNUM
		FROM
			T_GG_SJ_GOODS A,
			T_ZY_CK_CLEAR B
		WHERE
			A .GOODSID = B.GOODSID
		AND A .DEPTID = '101'
		AND CREATDATE >= TO_DATE ('2012/7/2', 'YYYY-MM-DD')
		GROUP BY
			OWNERID,
			OWNERNAME,
			MANAGENO,
			GOODSOWNERMANAGENO,
			A .PACKNUM,
			GRADENUM,
			GOODSLOCID,
			KINDNAME,
			SHOPSIGNNAME,
			PRODAREANAME,
			FIRSTINDATE
			
	UNION ALL
	
		SELECT
			OWNERID,
			OWNERNAME,
			MANAGENO,
			GOODSOWNERMANAGENO,
			PACKNUM,
			GRADENUM,
			GOODSLOCID,
			KINDNAME,
			SHOPSIGNNAME,
			PRODAREANAME,
			FIRSTINDATE,
			0 GRADENUMXH,
			0 SINGLESHEETNUM,
			SUM (NETWEIGHT) NETWEIGHT,
			SUM (GROSSWEIGHT) GROSSWEIGHT,
			SUM (SHEETNUM) SHEETNUM
		FROM
			T_ZY_JG_PROCMATERIALDTL
		WHERE
			DEPTID = '101'
		AND EXISTS (
			SELECT
				1
			FROM
				T_ZY_JG_PROCESS
			WHERE
				PROCESSID = T_ZY_JG_PROCMATERIALDTL.PROCESSID
			AND DEPTID = T_ZY_JG_PROCMATERIALDTL.DEPTID
			AND OUTCARBILLTIME >= TO_DATE ('2012/7/2', 'YYYY-MM-DD')
		)
		GROUP BY
			OWNERID,
			OWNERNAME,
			MANAGENO,
			GOODSOWNERMANAGENO,
			PACKNUM,
			GRADENUM,
			GOODSLOCID,
			KINDNAME,
			SHOPSIGNNAME,
			PRODAREANAME,
			FIRSTINDATE
			
	UNION ALL
	
		SELECT
			PREOWNERNO OWNERID,
			PROOWNERNAME OWNERNAME,
			PREMANAGENUM MANAGENO,
			GOODSOWNERMANAGENO,
			PACKNUM,
			GRADENUM,
			GOODSLOCID,
			KINDNAME,
			SHOPSIGNNAME,
			PRODAREANAME,
			FIRSTINDATE,
			0 GRADENUMXH,
			0 SINGLESHEETNUM,
			SUM (NETWEIGHT) NETWEIGHT,
			SUM (GROSSWEIGHT) GROSSWEIGHT,
			SUM (SHEETNUM) SHEETNUM
		FROM
			(
				SELECT
					A .PREOWNERNO,
					A .PROOWNERNAME,
					B.PREMANAGENUM,
					B.NETWEIGHT,
					B.GROSSWEIGHT,
					B.SHEETNUM,
					B.SHOPSIGNID,
					B.SHOPSIGNNAME,
					B.PRODAREAID,
					B.PRODAREANAME,
					B.GRADENUM,
					B.FIRSTINDATE,
					B.KINDNAME,
					B.GOODSLOCID,
					B.PACKNUM,
					B.PREGOODSOWNERMANAGENUM GOODSOWNERMANAGENO
				FROM
					(
						SELECT
							DEPTID,
							CHANGEOWNERID,
							PREOWNERNO,
							PROOWNERNAME
						FROM
							T_ZY_GH_CHANGEOWNERLIST
						WHERE
							DEPTID = '101'
						AND CHANGEDATE >= TO_DATE ('2012/7/2', 'YYYY-MM-DD')
					) A,
					T_ZY_GH_CHANGEOWNERDETAIL B
				WHERE
					A .CHANGEOWNERID = B.CHANGEOWNERNO  
				AND A .DEPTID = B.DEPTID
			) TB1
		GROUP BY
			PREOWNERNO,
			PROOWNERNAME,
			PREMANAGENUM,
			GOODSOWNERMANAGENO,
			PACKNUM,
			GRADENUM,
			GOODSLOCID,
			KINDNAME,
			SHOPSIGNNAME,
			PRODAREANAME,
			FIRSTINDATE
	) TBX
WHERE
	OWNERID = 'KH05821'
AND NETWEIGHT <> 0
GROUP BY
	OWNERID,
	OWNERNAME,
	MANAGENO,
	GOODSOWNERMANAGENO,
	PACKNUM,
	GRADENUM,
	GOODSLOCID,
	KINDNAME,
	SHOPSIGNNAME,
	PRODAREANAME,
	FIRSTINDATE
	
