use db;
create schema T_ZY_JG_PROCARTICLEDTL_schema
source type CSV
fields(
 "procarticledtlid" type str,
 "deptid" type str,
 "processid" type str,
 "packnum" type str,
 "barcode" type str,
 "goodslocid" type str,
 "ownerid" type str,
 "ownername" type str,
 "goodsownermanageno" type str,
 "goodsownerpackno" type str,
 "manageno" type str default value "0" ,
 "feebegindate" type DATETIME,
 "contractid" type str,
 "goodsstateno" type str,
 "goodsstatename" type str,
 "changeownertimes"  type double,
 "goodstype"          type str,
 "goodstypename"    type str,
 "kindno"    type str,
 "kindname"    type str,
 "shopsignid"    type str,
 "shopsignname"    type str,
 "prodareaid"    type str,
 "prodareaname"    type str,
 "goodsbatchno"    type str,
 "prodstoveno"    type str,
 "gradenum"    type str,
 "gradenumthick"     type double,
 "gradenumwidth"     type double,
 "gradenumlength"     type double,
 "grossweight"     type double,
 "netweight"     type double,
 "poundweight"     type double,
 "checkweight"     type double,
 "sheetnum"     type double,
 "packtype"     type str,
 "packtypename"    type str,
 "unit"    type str,
 "qualitymemo"    type str,
 "firstinownerid"    type str,
 "firstindate"     type DATETIME,
 "printflag"     type str,
 "quality"    type str,
 "qamember"    type str,
 "qaflag"     type str,
 "processqualityid"    type str,
 "r_record_create_date" type DATETIME,
 "r_record_create_user" type str,
 "r_record_update_date" type DATETIME,
 "r_record_update_user" type str,
 "r_record_is_deleted"  type double,
 "orderby"              type double,
 "r_record_change_flag" type double,
 "instruction_id"      type str,
 "sendflag"             type double,
 "acceptance_times"     type double,
 "acceptancer"         type str,
 "acceptance_time"      type DATETIME,
 "skinweight"      type double,
 "cyyweight"      type double,
 "goodsid"     type str,
 "articlememo1"     type str,
 "articlememo2"     type str,
 "articlememo3"      type str,
 "articlememo4"     type str,
 "articlememo5"     type str,
 "articlememo6"     type str,
 "articlememo7"     type str,
 "articlememo8"     type str,
 "articlememo9"     type str,
 "articlememo10"     type str,
 "articleys"     type str,
 "customerid"     type str,
 "cbxjgtype"     type str,
 "wallwidth"      type double,
 "woodtype"     type str,
 "woodtypename"     type str,
 "chanxian"     type str,
 "drawno"     type str,
 "zcflag"     type str default value "0",
 "classgroup"     type str,
 "loclv1"     type str,
 "loclv2"     type str
)          
RECORD DELIMITER "CRLF"
FIELD DELIMITER ","
TEXT QUALIFIER "NULL";
CREATE PARSER T_ZY_JG_PROCARTICLEDTL_parser
TYPE rcd
SCHEMA T_ZY_JG_PROCARTICLEDTL_schema;
CREATE TABLE T_ZY_JG_PROCARTICLEDTL using T_ZY_JG_PROCARTICLEDTL_parser;
CREATE INDEX T_ZY_JG_PROCARTICLEDTL_index ON TABLE T_ZY_JG_PROCARTICLEDTL(customerid);    